- name: Update web servers
  hosts: appservers
  become: true
  tasks:
  - name: Clone github repository
    git:
      repo: https://github.com/AlejandroPM96/mongo-sample.git
      dest: /home/app/
      clone: yes
      update: yes
  - name: install pip3
    apt: name=python3-pip state=present update_cache=yes

  - name: Install specified python requirements offline from a local directory with downloaded packages
    pip:
      requirements:  /home/app/requirements.txt
  - name: start flask
    shell: "nohup python3 /home/app/app.py &"
    environment:
      FLASK_APP: /home/app/app.py
      MONGO_URI: mongodb://127.0.0.1:27017/